version: 0.0
os: linux

#!/bin/bash

# Define the directory where artifacts are stored
ARTIFACTS_DIR=/home/ec2-user/

# Remove previous artifacts
sudo rm -rf my-app

files:
  - source: s3://ngs-bucket7/MyFirstPipeline/BuildArtif/39jQ90m
    destination: /home/ec2-user/my-app
permissions:
  - object: /home/ec2-user/my-app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: root
