version: 0.0
os: linux

files:
  - source: s3://ngs-bucket7/test_pipeline/deployment/my-application-deployment.zip
    destination: /home/ec2-user/my-app
    overwrite: true   # Optional: Specify whether to overwrite existing files in the destination
permissions:
  - object: /home/ec2-user/my-app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: root
